image: hardtyz/jre-mvn-py3

pipelines:
  branches:
    master:
      - step:
          caches:
            - maven
            - node
          script:
            - mvn clean install # package up the application for deployment
            - pip install boto3==1.3.0 # required for beanstalk_deploy.py
            - mkdir -p /tmp # create temporary directory
            - find /opt/atlassian/pipelines/agent/build/target -type f -name "api-*.jar" |head -1|xargs cp -t "/tmp" # move jar to temporary directory
            - find /tmp -type f -name "api-*.jar" -exec mv {} /tmp/artifact.jar \; # rename jar to artifact
            - python3 beanstalk_deploy.py # run the deployment script