## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource: 
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

# Show or not log for each sql query
    show-sql: false

# Hibernate ddl auto (create, create-drop, validate, update)S
    hibernate:
      ddl-auto: validate

# Jackson
# spring.jackson.time-zone = America/Sao_Paulo

  thymeleaf:
    template-resolver-order: 0
    cache: false

---

spring:
  profiles: dev
  
  
---

spring:
  profiles: prod